defaults:
  - &default_license
    license: "CC-BY-4.0"

save_dir: ???

# Data bounds and download configuration
min_latitude: 0.0
max_latitude: 90.0
min_longitude: -180.0
max_longitude: 180.0
min_depth: 0.0
max_depth: 5000.0
license: null # se t to null to get any license
start_time: "2022-01-01T00:00:00Z"
end_time: "2022-01-02T00:00:00Z"
